# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: El Blog del Aleman
email: pablo.niklas _at_ gmail _dot_ com
description: >- # this means to ignore newlines until "baseurl:"
  Un blog donde dejo exposición de algunos temas, como así tambien, algunos trucos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pabloniklas.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title

#twitter_username: pabloniklas
#github_username: pabloniklas

site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pablo Niklas # add your name
author-img: pn_ninja.png # add your photo
about-author: Graduate. University Teacher. Linux user from the begining. Retroinformatic lover. Besides from, photography, Jazz, Swing, and Classic Eurodance.
social-twitter: pabloniklas
social-facebook: # add your Facebook handle
social-github: pabloniklas # add your Github handle
social-linkedin: # add your Linkedin handle
social-email:

analytics: UA-45392322-2

# Build settings
# remote_theme: Phlow/feeling-responsive
markdown: kramdown
remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
